# frozen_string_literal: true

require 'rails_helper'

RSpec.describe TodosController, type: :controller do
  describe 'POST #highlight' do
    it 'broadcasts a dispatch payload for highlighting the todo row in js format' do
      user = create(:user)
      todo = create(:todo, user_id: user.id)

      allow(controller).to receive(:authenticate_user!).and_return(true)
      allow(controller).to receive(:current_user).and_return(user)
      expected_target = "##{ActionView::RecordIdentifier.dom_id(todo)}"
      expected_stream_key = "resource:todo:user:#{user.id}"

      allow(SecureRandom).to receive(:uuid).and_return('uuid-highlight')
      expect(ActionCable.server).to receive(:broadcast).with(
        expected_stream_key,
        hash_including(
          action: 'dispatch',
          target: expected_target,
          content: nil,
          id: 'uuid-highlight',
          event_name: 'todo:highlight',
          event_data: { id: todo.id, title: todo.title }
        )
      )

      post :highlight, params: { id: todo.id }, format: :js

      expect(response).to have_http_status(:ok)
      expect(response.body).to be_empty
    end

    it 'broadcasts a dispatch payload for highlighting the todo row in json format' do
      user = create(:user)
      todo = create(:todo, user_id: user.id)

      allow(controller).to receive(:authenticate_user!).and_return(true)
      allow(controller).to receive(:current_user).and_return(user)
      expected_target = "##{ActionView::RecordIdentifier.dom_id(todo)}"
      expected_stream_key = "resource:todo:user:#{user.id}"

      allow(SecureRandom).to receive(:uuid).and_return('uuid-highlight-json')
      expect(ActionCable.server).to receive(:broadcast).with(
        expected_stream_key,
        hash_including(
          action: 'dispatch',
          target: expected_target,
          content: nil,
          id: 'uuid-highlight-json',
          event_name: 'todo:highlight',
          event_data: { id: todo.id, title: todo.title }
        )
      )

      post :highlight, params: { id: todo.id }, format: :json

      expect(response).to have_http_status(:ok)
      expect(response.body).to be_empty
    end

    it 'rejects unsupported formats' do
      user = create(:user)
      todo = create(:todo, user_id: user.id)

      allow(controller).to receive(:authenticate_user!).and_return(true)
      allow(controller).to receive(:current_user).and_return(user)

      expect do
        post :highlight, params: { id: todo.id }, format: :html
      end.to raise_error(ActionController::UnknownFormat)
    end
  end

  describe 'GET #datatable' do
    render_views

    it 'renders destacar action as a post form button' do
      user = create(:user)
      todo = create(:todo, user_id: user.id)

      allow(controller).to receive(:authenticate_user!).and_return(true)
      allow(controller).to receive(:current_user).and_return(user)

      get :datatable

      html = Nokogiri::HTML(response.body)
      form = html.at_css("form[action='#{highlight_todo_path(todo, format: :js)}']")

      expect(form).not_to be_nil
      expect(form['method']).to eq('post')
      expect(form.at_css("button[type='submit']")&.text.to_s).to include('Destacar')
    end
  end

  describe 'GET #dom_id_probe' do
    it 'returns dom_id generated by helper with prefix and suffix wrappers' do
      user = create(:user)
      todo = create(:todo, user_id: user.id)

      allow(controller).to receive(:authenticate_user!).and_return(true)
      allow(controller).to receive(:current_user).and_return(user)

      get :dom_id_probe, params: { id: todo.id }

      expect(response).to have_http_status(:ok)
      expect(response.body).to eq("row_todo_#{todo.id}_flash")
      expect(response.body).not_to eq("row_#{todo.id}_flash")
    end
  end
end
